Code Review Request for Design Teardwn Project
KartheekWD/Design-Teardown pull request #6
Opened 2020-07-21 18:57 UTC by KartheekWD

Requesting a code review of our Smashing Magazine clone project. Thank you! ~KartheeK and Nik.

2020-07-21 19:38 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

- I see that you have added images to your project. Please add a placeholder (a `div` with height, width, and background-color) instead of an actual image. The reason behind this is:

  - You are making a mockup of a website, not the actual site. Just like how you have highlighted each section, highlight the part where images should go and how big the image should be.

- There is a horizontal scrollbar in your heatmap. Please remove this 👇 

  ![image](https://user-images.githubusercontent.com/57726348/88098172-f7cb3e80-cbb6-11ea-9634-d83a6f9aa3dc.png)

- These sections are missing from your heatmap. Please add them 👇 

  ![image](https://user-images.githubusercontent.com/57726348/88098588-a1aacb00-cbb7-11ea-99c7-12366d60f6ec.png)

  ![image](https://user-images.githubusercontent.com/57726348/88098414-614b4d00-cbb7-11ea-8e3a-382130d18f59.png)

  ![image](https://user-images.githubusercontent.com/57726348/88098505-82ac3900-cbb7-11ea-819a-493818da6086.png)


Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-07-22 10:32 UTC, nikoescobal commented
Hi @tirthajyoti-ghosh! Thank you for taking the time to review our code and for the encouraging words! 😊

We've implemented the change requests you mentioned earlier regarding changing images to div placeholders and the screenshot concern. As you can see below, there seems to be no horizontal scrollbar on my screen.

<img width="1440" alt="Screen Shot 2020-07-22 at 5 02 21 PM" src="https://user-images.githubusercontent.com/62937819/88165037-a61ec480-cc47-11ea-9d8b-ebc260a46737.png">
 
I'd like to point out that it was by design that Kartheek and I did not build those sections, as these are ads not central to the visual hierarchy of the page, unlike sections that link to articles, the main content.  

🙏🏽 Your consideration is very much appreciated. 🙏🏽 Hope you're having a great day! 😊

2020-07-22 11:27 UTC, kitpao requested changes
# :wave: Hello @nikoescobal and @KartheekWD 

As my previous colleague said, you did pretty great! 🌟 You went ahead ad added the hover effects that of course, grab the attention of the user, nicely done 😎

For changes and suggestions, please see below and in the inline reviews ⬇️

- [ ] **[MANDATORY]** About the missing sections, even if the ads are not eye catching, you have to respect their space (put a blank space if you will). Remember this is the heatmap clone of the original and the layout is an important part since that's the first thing a user sees. For example in the article section, the original layout is: 3 articles, then 2 articles to the right, and lastly 2 articles to the left. You have: 3 articles, 3 articles, 1 article.
![image](https://user-images.githubusercontent.com/53256139/88170194-e8fa8100-cbe2-11ea-960a-0189d6bab9cd.png)

### ♻️ Status: Your project requires some additional changes ♻️
Keep up the good work 👏
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-22 11:27 UTC, kitpao commented on README.md
> +[Live Demo Link](https://rawcdn.githack.com/KartheekWD/Design-Teardown/d18fd57c6a2cb0c71e9a710bee9de920c57782ab/index.html)
- [ ] **[OPTIONAL]** In order to have a professional readme, an updated link is always better. As a suggestion, so you don't have to be manually updating this link during your code reviews, use the second link (development) link in githack, that one will load automatically your last version in the same branch :)

2020-07-22 11:27 UTC, kitpao commented on style.css
> +  width: 100vw;
- [ ] **[Mandatory]** The problem of your horizontal scrollbar is due to the `width: 100vh;` rule, that will make your page as big as the screen BUT you are forgetting that the automatic vertical scrollbar also has a width, so you will always be missing that space. (It is weird that it isn't showing for you, maybe your task bar is accidentally above it) Just delete that line since you already defined your min-width in the next line
![image](https://user-images.githubusercontent.com/53256139/88168614-4b9e4d80-cbe0-11ea-908f-2e46d994c9e2.png)

2020-07-22 19:54 UTC, nikoescobal commented
@kitpao Thank you for your feedback on our project. We've gone ahead and built out the missing sections as you requested.

2020-07-22 20:02 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

#### Great job working on the changes asked by my colleagues. As they already said, the page looks awesome!

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-23 06:47 UTC, merged